import type { Metadata } from "next";
import "./globals.css";
import LenisScript from "./components/LenisScript";
import Cursor from "./components/Cursor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://unpkg.com/lenis@1.2.3/dist/lenis.css" />
        <script src="https://unpkg.com/lenis@1.2.3/dist/lenis.min.js" defer></script>
      </head>
      <body className="antialiased">
        <Cursor />
        {children}
        <LenisScript />
      </body>
    </html>
  );
}
